import { Inter } from "next/font/google";
import { Providers } from "../providers";
// Inter fontunu yalnızca bir obje olarak içe aktarın
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function LoginLayout({ children, params:{locale}}) {
  return (
  
    <html >
      <body >
        <Providers>
            {children}
        </Providers>
      </body>
    </html>
  );
}
